package com.unionpay.upomp.bypay.other;

import android.app.Activity;
import android.content.Context;
import android.widget.Button;
import android.widget.EditText;
import java.util.ArrayList;
import java.util.List;

public class eh
{
  public static String A;
  public static String B;
  public static String C;
  public static String D;
  public static String E;
  public static String F;
  public static String G;
  public static String H;
  public static String I;
  public static String J;
  public static String K;
  public static String L;
  public static String M;
  public static String N;
  public static String O;
  public static String P;
  public static String Q;
  public static String R;
  public static String S;
  public static String T;
  public static String U;
  public static String V;
  public static String W;
  public static String X;
  public static String Y;
  public static String Z;
  public static byte a;
  public static int a;
  public static Activity a;
  public static Context a;
  public static Button a;
  public static EditText a;
  public static af a;
  public static bh a;
  public static ct a;
  public static fv a;
  public static Boolean a;
  public static String a;
  public static ArrayList a;
  public static List a;
  public static boolean a;
  public static String[] a;
  public static String aA;
  public static String aB;
  public static String aC;
  public static String aD;
  public static String aE;
  public static String aF;
  public static String aG;
  public static String aH;
  public static String aI;
  public static String aJ;
  public static String aK;
  public static String aL;
  public static String aM;
  public static String aN;
  public static String aO;
  public static String aP;
  public static String aa;
  public static String ab;
  public static String ac;
  public static String ad;
  public static String ae;
  public static String af;
  public static String ag;
  public static String ah;
  public static String ai;
  public static String aj;
  public static String ak;
  public static String al;
  public static String am;
  public static String an;
  public static String ao;
  public static String ap;
  public static String aq;
  public static String ar;
  public static String as;
  public static String at;
  public static String au;
  public static String av;
  public static String aw;
  public static String ax;
  public static String ay;
  public static String az;
  public static byte b;
  public static int b;
  public static Boolean b;
  public static String b;
  public static boolean b;
  public static String[] b;
  public static byte c;
  public static int c;
  public static Boolean c;
  public static String c;
  public static boolean c;
  public static String[] c;
  public static byte d;
  public static int d;
  public static Boolean d;
  public static String d;
  public static boolean d;
  public static String[] d;
  public static int e;
  public static Boolean e;
  public static String e;
  public static boolean e;
  public static String[] e;
  public static int f;
  public static Boolean f;
  public static String f;
  public static boolean f;
  public static String[] f;
  public static int g;
  public static Boolean g;
  public static String g;
  public static boolean g;
  public static String[] g;
  public static int h;
  public static Boolean h;
  public static String h;
  public static boolean h;
  public static String[] h;
  public static int i;
  public static String i;
  public static boolean i;
  public static String[] i;
  public static int j;
  public static String j;
  public static boolean j;
  public static String[] j;
  public static int k;
  public static String k;
  public static boolean k;
  public static String[] k;
  public static int l;
  public static String l;
  public static boolean l;
  public static String[] l;
  public static int m;
  public static String m;
  public static boolean m;
  public static String[] m;
  public static int n;
  public static String n;
  public static String[] n;
  public static int o;
  public static String o;
  public static String[] o;
  public static int p;
  public static String p;
  public static String[] p;
  public static int q;
  public static String q;
  public static String[] q;
  public static int r;
  public static String r;
  public static String[] r;
  public static int s;
  public static String s;
  public static int t;
  public static String t;
  public static int u;
  public static String u;
  public static int v;
  public static String v;
  public static String w;
  public static String x;
  public static String y;
  public static String z;
  
  static
  {
    jdField_a_of_type_Boolean = true;
    jdField_b_of_type_Boolean = true;
    jdField_c_of_type_Boolean = true;
    jdField_a_of_type_Int = 0;
    jdField_d_of_type_Boolean = false;
    jdField_b_of_type_Int = -1;
    jdField_c_of_type_Int = -1;
    jdField_a_of_type_JavaLangString = "";
    jdField_a_of_type_AndroidWidgetEditText = null;
    jdField_a_of_type_AndroidWidgetButton = null;
    jdField_b_of_type_JavaLangString = "";
    jdField_c_of_type_JavaLangString = "";
    jdField_a_of_type_JavaLangBoolean = Boolean.valueOf(false);
    jdField_b_of_type_JavaLangBoolean = Boolean.valueOf(false);
    jdField_d_of_type_JavaLangString = "";
    jdField_d_of_type_Int = 0;
    jdField_a_of_type_ComUnionpayUpompBypayOtherCt = new ct();
    jdField_e_of_type_Boolean = true;
    jdField_e_of_type_JavaLangString = "";
    jdField_f_of_type_JavaLangString = "";
    jdField_g_of_type_JavaLangString = "";
    jdField_h_of_type_JavaLangString = "X7fyntm7";
    jdField_i_of_type_JavaLangString = "7v5qahEtY1C82ghqvP73GQ==";
    jdField_j_of_type_JavaLangString = "config";
    jdField_k_of_type_JavaLangString = "telnormal";
    jdField_l_of_type_JavaLangString = "";
    jdField_f_of_type_Boolean = false;
    jdField_m_of_type_JavaLangString = "";
    jdField_n_of_type_JavaLangString = "1";
    jdField_o_of_type_JavaLangString = "";
    jdField_p_of_type_JavaLangString = "";
    jdField_q_of_type_JavaLangString = "";
    jdField_r_of_type_JavaLangString = "";
    jdField_s_of_type_JavaLangString = "";
    jdField_t_of_type_JavaLangString = "";
    u = "";
    jdField_v_of_type_JavaLangString = "";
    w = "PluginInit.Req";
    x = "1.0.0";
    y = "";
    z = "";
    A = "";
    B = "";
    C = "";
    D = "";
    E = "";
    F = "1";
    G = "2";
    H = "02-02-1.0.0";
    I = "";
    J = "3";
    K = "1";
    L = "";
    M = "";
    N = "";
    O = "";
    P = "";
    Q = "";
    R = "";
    S = "";
    T = "";
    U = "";
    V = "";
    W = "";
    X = "";
    Y = "";
    Z = "";
    aa = "";
    ab = "";
    ac = "";
    ad = "";
    ae = "";
    af = "";
    ag = "1";
    ah = "";
    ai = "";
    aj = "88888888";
    ak = "";
    jdField_e_of_type_Int = 0;
    al = "";
    am = "1";
    an = "1";
    ao = "";
    ap = "1";
    aq = "";
    ar = "";
    jdField_g_of_type_Boolean = false;
    as = "1";
    at = "";
    au = "";
    av = "";
    aw = "";
    jdField_h_of_type_Boolean = false;
    jdField_i_of_type_Boolean = false;
    jdField_j_of_type_Boolean = false;
    jdField_c_of_type_JavaLangBoolean = Boolean.valueOf(false);
    ax = "1";
    ay = null;
    jdField_d_of_type_JavaLangBoolean = Boolean.valueOf(false);
    az = "";
    jdField_f_of_type_Int = 1;
    aA = "";
    aB = "";
    aC = "";
    aD = "";
    aE = "";
    aF = "";
    jdField_g_of_type_Int = 0;
    jdField_h_of_type_Int = 0;
    aG = "";
    aH = "";
    jdField_k_of_type_Boolean = false;
    jdField_l_of_type_Boolean = true;
    jdField_i_of_type_Int = 0;
    jdField_j_of_type_Int = 0;
    jdField_k_of_type_Int = 0;
    jdField_l_of_type_Int = -1;
    jdField_m_of_type_Int = 0;
    jdField_n_of_type_Int = 0;
    jdField_o_of_type_Int = -1;
    jdField_p_of_type_Int = 0;
    jdField_q_of_type_Int = 0;
    jdField_e_of_type_JavaLangBoolean = Boolean.valueOf(false);
    aI = "";
    aJ = "";
    aK = "";
    jdField_n_of_type_ArrayOfJavaLangString = new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" };
    jdField_o_of_type_ArrayOfJavaLangString = new String[] { "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" };
    aL = "2011";
    jdField_p_of_type_ArrayOfJavaLangString = new String[] { "upomp_bypay_add_card", "upomp_bypay_card_balance", "upomp_bypay_edit_pass", "upomp_bypay_get_pass", "upomp_bypay_keyboard", "upomp_bypay_login", "upomp_bypay_pay_it", "upomp_bypay_register" };
    jdField_q_of_type_ArrayOfJavaLangString = new String[] { "" };
    jdField_a_of_type_JavaUtilList = null;
    jdField_r_of_type_ArrayOfJavaLangString = null;
    jdField_r_of_type_Int = 0;
    jdField_s_of_type_Int = 0;
    jdField_a_of_type_Byte = 0;
    jdField_t_of_type_Int = 20000;
    aO = "";
    jdField_f_of_type_JavaLangBoolean = Boolean.valueOf(false);
    jdField_g_of_type_JavaLangBoolean = Boolean.valueOf(false);
    jdField_b_of_type_Byte = 0;
    jdField_c_of_type_Byte = 0;
    jdField_d_of_type_Byte = 0;
    jdField_h_of_type_JavaLangBoolean = Boolean.valueOf(true);
    aP = "/rUWWIAcMGCCLkR4JIJXDQ==";
    jdField_v_of_type_Int = 0;
  }
}


/* Location:           C:\Users\yepeng\Documents\classes-dex2jar.jar
 * Qualified Name:     com.unionpay.upomp.bypay.other.eh
 * JD-Core Version:    0.7.0.1
 */